- name: ros | ws management tools
  pip:
    executable: pip3
    name:
      - vcstool

- name: ros | install linters
  pip:
    executable: pip3
    name:
      - flake8
      - flake8-blind-except
      - flake8-builtins
      - flake8-class-newline
      - flake8-comprehensions
      - flake8-deprecated
      - flake8-docstrings
      - flake8-import-order
      - flake8-quotes

- name: ros | install docker tools
  pip:
    executable: pip3
    name:
      - rocker
      - off-your-rocker
      - ros_cross_compile
